### Generated by Winemaker 0.8.4
###
### Invocation command line was
### /usr/bin/winemaker --interactive --nomsvcrt .


SRCDIR                = .
SUBDIRS               =
DLLS                  = g29range.dll
LIBS                  =
EXES                  =



### Common settings

CEXTRA                = -Wall
CXXEXTRA              = -Wall
RCEXTRA               =
DEFINES               =
INCLUDE_PATH          = -I.
DLL_PATH              =
DLL_IMPORTS           =
LIBRARY_PATH          =
LIBRARIES             = -ludev


### g29range.dll sources and settings

g29range_dll_MODULE   = g29range.dll
g29range_dll_C_SRCS   = G29Range.c
g29range_dll_CXX_SRCS =
g29range_dll_RC_SRCS  =
g29range_dll_LDFLAGS  = -shared \
			$(g29range_dll_MODULE:.dll=.spec)
g29range_dll_ARFLAGS  =
g29range_dll_DLL_PATH =
g29range_dll_DLLS     = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
g29range_dll_LIBRARY_PATH=
g29range_dll_LIBRARIES= uuid \
			udev

g29range_dll_OBJS     = $(g29range_dll_C_SRCS:.c=.o) \
			$(g29range_dll_CXX_SRCS:.cpp=.o) \
			$(g29range_dll_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(g29range_dll_C_SRCS)
CXX_SRCS              = $(g29range_dll_CXX_SRCS)
RC_SRCS               = $(g29range_dll_RC_SRCS)


### Tools

CC = winegcc
CXX = wineg++
RC = wrc
AR = ar


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(LIBS) $(EXES)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .cpp .cxx .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(LIBS) $(EXES) $(EXES:%=%.so)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH) $(DLL_IMPORTS:%=-l%)

$(g29range_dll_MODULE).so: $(g29range_dll_OBJS) $(g29range_dll_MODULE:.dll=.spec)
	$(CC) $(g29range_dll_LDFLAGS) -o $@ $(g29range_dll_OBJS) $(g29range_dll_LIBRARY_PATH) $(g29range_dll_DLL_PATH) $(DEFLIB) $(g29range_dll_DLLS:%=-l%) $(g29range_dll_LIBRARIES:%=-l%)


